name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - SmallMenu/**
    - SmallMenu.sln

jobs:
  build:
    name: SmallMenu
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@v1
      with:
        access-token: ${{ secrets.BEAT_SABER_REFERENCE_ASSEMBLIES_TOKEN }}
        project-path: ${{ github.workspace }}\SmallMenu\SmallMenu.csproj

    - name: Build Release
      id: build-release
      run: dotnet build ${{ github.workspace }}\SmallMenu\SmallMenu.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}
